//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroReceta
    {
        public short idReceta { get; set; }
        public short idRegistro { get; set; }
        public string cedulaNutriologo { get; set; }
    
        public virtual Nutriologo Nutriologo { get; set; }
        public virtual Receta Receta { get; set; }
    }
}
